from llama_index import ServiceContext, VectorStore, SimpleDirectoryReader
import pdfplumber

# Check available methods from llama_index
import llama_index
print(dir(llama_index))

# Function to extract text from the PDF
def extract_pdf_text(pdf_path):
    with pdfplumber.open(pdf_path) as pdf:
        text = ""
        for page in pdf.pages:
            text += page.extract_text()
        return text

# Path to your PDF file
file_path = "C:/Users/ilhem/Downloads/TW-Formation Métiers (1).pdf"  # Ensure the path is correct
pdf_text = extract_pdf_text(file_path)

# Save the extracted text into a file for LLaMA
with open("pdf_text.txt", "w") as f:
    f.write(pdf_text)

# Load the extracted text using SimpleDirectoryReader for indexing
documents = SimpleDirectoryReader("pdf_text.txt").load_data()

# Create a VectorStore index using the documents
service_context = ServiceContext.from_documents(documents)
index = VectorStore.from_documents(documents, service_context)

# Create a system prompt to avoid deprecated warning
system_prompt = "Voici un texte de formation sur les crédits. Posez des questions et obtenez des réponses basées sur ce texte."

# Use the new `system_prompt` parameter instead of `parsing_instruction`
query = "Qu'est-ce qu'un crédit ?"
response = index.query(query, system_prompt=system_prompt)

# Display the response generated by LLaMA
print(response)